# Generated by Django 3.2 on 2021-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_saying',
            field=models.CharField(default='WHERE PHOTOGRAPHERS INSPIRE EACH OTHER', max_length=50),
        ),
    ]
