# Generated by Django 3.2 on 2021-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0002_alter_home_home_saying'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('about_icon', models.ImageField(upload_to='about/images')),
                ('about_keshav', models.CharField(max_length=300)),
                ('exp_nature', models.CharField(max_length=300)),
                ('exp_event', models.CharField(max_length=300)),
                ('exp_portait', models.CharField(max_length=300)),
                ('exp_life', models.CharField(max_length=300)),
                ('skils_info', models.CharField(max_length=200)),
                ('skils_dev', models.IntegerField(default=60)),
                ('skils_photography', models.IntegerField(default=60)),
                ('skils_dynamic', models.IntegerField(default=60)),
                ('skils_classic', models.IntegerField(default=60)),
            ],
        ),
    ]
