# Generated by Django 3.2 on 2021-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0003_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='exp_portait',
        ),
        migrations.AddField(
            model_name='about',
            name='exp_blackwhite',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='exp_portrait',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_keshav',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='exp_event',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='exp_life',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='exp_nature',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='skils_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
