# Generated by Django 3.2 on 2021-04-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0004_auto_20210425_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='skils_classic',
            new_name='skills_classic',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='skils_dev',
            new_name='skills_dev',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='skils_dynamic',
            new_name='skills_dynamic',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='skils_info',
            new_name='skills_info',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='skils_photography',
            new_name='skills_photography',
        ),
    ]
