# Generated by Django 3.2 on 2021-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0005_auto_20210425_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='gallery/images')),
                ('gallery_img_type', models.CharField(default='Portrait', max_length=10)),
                ('gallery_img_name', models.CharField(default='Gallery Image', max_length=15)),
                ('gallery_img_desc', models.CharField(default='Gallery Image Description', max_length=20)),
            ],
        ),
    ]
