# Generated by Django 3.2 on 2021-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_img_desc',
            field=models.CharField(default='Gallery Image Description', max_length=30),
        ),
    ]
