# Generated by Django 3.2 on 2021-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0009_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=22)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=300)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
