# Generated by Django 3.2 on 2021-04-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='datetime',
        ),
    ]
