# Generated by Django 3.2.5 on 2021-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
