# Generated by Django 3.2.5 on 2021-07-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='test',
        ),
    ]
